spring:
  application:
    name: mscartoes
  rabbitmq:
    host: ${RABBITMQ_SERVER}
    port: 5672
    username: guest
    password: guest

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://cursoms-eureka-user:uusk-rusreee-csraom@${EUREKA_SERVER}:8761/eureka #url registro o ms no eureka com docker
      ##defaultZone: http://cursoms-eureka-user:uusk-rusreee-csraom@localhost:8761/eureka #url registro o ms no eureka
  instance: # registrando instancia com nome de forma randomica
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

mq:
  queues:
    emissao-cartoes: emissao-cartoes

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file:
    name: ./logs/log-file.log